server:
  port: 8083
security:
  enable:
    csrf: false
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: anime-service-id
          uri: lb://anime-service
          predicates:
            - Path=/animeservice/**
        - id: episode-service-id
          uri: lb://episode-service
          predicates:
            - Path=/episodeservice/**
        - id: personnage-service-id
          uri: lb://personnage-service
          predicates:
            - Path=/personnageservice/**
        - id: utilisateur-service-id
          uri: lb://utilisateur-service
          predicates:
            - Path=/utilisateurservice/**
## App Properties
app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000
