server:
  port: 8081
  servlet:
    context-path: /utilisateurservice

spring:
  h2:
    console.enabled: true # pour afficher la console H2 http://localhost:8081/utilisateurservice/h2-console/
  datasource:
    url: jdbc:h2:mem:testdb #url de la base de données
    driverClassName: org.h2.Driver #driver h2
    username: sa
    password: password
  jpa:
    show-sql: true # affiche les logs sql
    properties:
      hibernate:
        format_sql: true # format les logs sql
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # creer les tables si elles n'existent pas, sinon les mettre à jour

## App Properties
app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 3600000
