INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('One Piece', 'Aventure', 'Lhistoire de One Piece se déroule dans un monde fictif dominé par les océans, où certains pirates aspirent à une ère de liberté et d''aventure connue comme « l''âge d''or de la piraterie ». Cette époque fut inaugurée à la suite des derniers mots prononcés par le roi des pirates, Gol D. Roger, surnommé Gold Roger avant son exécution5. Roger annonce au monde que ses habitants étaient libres de chercher toutes les richesses qu''il avait accumulées durant sa vie entière, le « One Piece6. »

Vingt-deux ans après lexécution de Roger, lintérêt pour le One Piece s’effrite. Beaucoup y ont renoncé, certains se demandent même sil existe vraiment. Même si les pirates sont toujours une menace pour les habitants, la Marine est devenue plus efficace pour contrer leurs attaques sur les quatre mers : East Blue, North Blue, West Blue et South Blue. Pourtant, ce changement na pas dissuadé Monkey D. Luffy, un jeune garçon, de vouloir devenir le successeur du légendaire Roger. Il va ainsi partir à l’aventure en se donnant comme premier objectif de créer un équipage afin de rejoindre la mer de Grand Line, où la fièvre de la « grande vague de piraterie » continue de sévir, et où de nombreux grands noms de la piraterie sont à la poursuite du One Piece, supposé être sur la dernière île de cette grande mer, Laugh Tale (orthographe voulue par Oda).', 1014);


INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('Naruto', 'Action', 'L''histoire commence pendant l''adolescence de Naruto, vers ses douze ans. Orphelin cancre et grand farceur, il fait toutes les bêtises possibles pour se faire remarquer. Son rêve : devenir le meilleur Hokage afin d''être reconnu par les habitants de son village. En effet, le démon renard à neuf queues scellé en lui a attisé la crainte et le mépris des autres villageois, qui, avec le temps, ne font plus de différence entre Kyûbi et Naruto. Malgré cela, Naruto s''entraîne dur afin de devenir genin, le premier niveau chez les ninjas. Après avoir raté l''examen genin 3 fois, il arrive finalement à recevoir son bandeau frontal de Konoha. Il est alors inclus dans une équipe de trois apprentis ninjas, avec Sakura Haruno et le talentueux Sasuke Uchiwa qui veut venger les personnes chères à ses yeux, en tuant son frère Itachi Uchiwa. Peu après, ils rencontrent leur jōnin (ninja de classe supérieure), celui qui s''occupera de leur formation : le mystérieux Kakashi Hatake.

Au début craint et méprisé par ses pairs, Naruto va peu à peu monter en puissance et gagner le respect et l''affection des villageois grâce, notamment, aux combats dantesques qu''il remportera face aux ennemis les plus puissants de Konoha.', 720);

INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('Bleach', 'Surnaturel', 'Le récit commence en 2001 au Japon dans la ville fictive de Karakura. Ichigo Kurosaki, lycéen de 15 ans, arrive à voir, entendre et toucher les âmes des morts depuis qu''il est tout petit. Un soir, sa routine quotidienne vient à être bouleversée à la suite de sa rencontre avec une shinigami (死神?, littéralement « dieu de la mort »), Rukia Kuchiki, et la venue d''un monstre appelé hollow. Ce dernier étant venu dévorer les âmes de sa famille et la shinigami venue le protéger ayant été blessée par sa faute, Ichigo accepte de devenir lui-même un shinigami afin de les sauver.

Cependant, le transfert de pouvoir, censé être temporaire et partiel, est complet et ne s''achève pas. Ichigo est forcé de prendre la responsabilité de la tâche incombant à Rukia Kuchiki. Il commence donc la chasse aux hollows tout en protégeant les âmes humaines.

Le début est centré sur une chasse aux mauvais esprits relativement peu puissants, avec un simple sabre. L''histoire va peu à peu se diriger vers un vaste complot mystico-politique après l''apparition des premiers autres shinigami. Les batailles au sabre du commencement vont alors se métamorphoser en combats dantesques avec des armes aux pouvoirs surprenants et variés, et parfois aux proportions gigantesques.', 366);

INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('Hunter x Hunter', 'Aventure', 'Gon Freecss a douze ans, et rêve de devenir hunter (chasseur en anglais). Les hunters sont des citoyens d''élite autorisés à faire quasiment tout ce qu''ils souhaitent sur simple présentation de leur licence : ils peuvent ainsi acquérir gratuitement tout objet à la vente sur les fonds de l''association ; réquisitionner tout véhicule, logement et outil pour leur travail ; et sont de facto habilités à exercer tous les métiers du monde, pouvant tout aussi bien devenir chasseurs de primes, chefs-cuisinier, archéologues, zoologues, justiciers ou consultants dans divers domaines. Son père, Ging Freecss, qu''il ne connaît pas directement, est considéré comme un des plus grands hunters de son temps. C''est aussi pour le retrouver que Gon veut devenir hunter.

Cependant l''examen de hunter, qui a lieu chaque année, est extrêmement difficile et périlleux. On dit qu''un candidat sur 10 000 arrive sur le lieu des épreuves et qu''un seul candidat tous les trois ans devient hunter à sa première tentative. Durant les épreuves, il n''est pas rare d''être blessé, voire tué par des monstres, des pièges ou même d''autres concurrents…

Au cours de cet examen, Gon va rencontrer différents personnages, aussi bien amis qu''ennemis : Kurapika, dont le seul objectif est de venger son clan, le clan Kuruta, assassiné par la Brigade fantôme et tenter de récupérer les yeux de son clan, les pupilles écarlates ; Léolio, dont le but avoué est d''acquérir de l''argent pour financer ses études de médecine ; Kirua, qui a le même âge que Gon, fils d''une famille d''assassins d''élite, la famille Zoldik, ne souhaitant pas poursuivre la voie de sa famille, qui participe à cet examen par simple amour du défi ; Hisoka, dont la grande passion est le combat contre des guerriers très puissants ; ainsi que beaucoup d''autres…

La force de Gon n''est pas que physique : son charisme, sa pureté, sa gentillesse, sa grande générosité et surtout son incroyable capacité à attirer la sympathie l''aident souvent à se sortir des situations les plus périlleuses.',148);

INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('Shaman King', 'Action/Surnaturel', 'Manta est un collégien très ordinaire. Un jour, traversant un cimetière pour gagner du temps, il rencontre Yoh, un shaman. Yoh peut voir les fantômes, et fusionner avec eux pour utiliser leurs compétences. Son rêve est de devenir Shaman King, le shaman possédant le fantôme ultime, le Great Spirit, la connaissance universelle. Mais la route est semée d''embûches, et de nombreux autres shamans ont le même objectif : gagner le Shaman Fight.', 48);


INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('The Irregular at Magic High School', 'Magie/Romance', 'La série se déroule dans un monde uchronique, où la magie existe grâce à la technologie moderne depuis un premier cas avéré en 1999. Cependant, la capacité d''utiliser la magie est déterminée par la génétique, ce qui limite la quantité de magiciens existant. À la suite de la Troisième Guerre mondiale ayant eu lieu de 2045 à 2065, les superpuissances du monde ont changé vers ces quatre nations: les États-Unis d''Amérique du Nord (en anglais : United States of North America, (USNA), la Nouvelle Union soviétique, la Grande Alliance asiatique et le Japon. Au Japon, la communauté magique est contrôlée de façon officieuse par les Dix Clans maîtres au lieu du gouvernement. En raison du nombre limité de magiciens, ils sont traités comme de la marchandise et sont forcés d''entrer dans des écoles et des professions liées à la magie. Neuf lycées magiques existent au Japon ; ils se spécialisent chacun dans différents aspects de la magie et sont simplement désignés par leurs nombres.

L''histoire suit celle de Tatsuya Shiba, un garde du corps de sa sœur Miyuki Shiba qui est également une candidate pour prendre la suite d''un des Dix Clans, les Yotsuba. En 2095, ils se sont inscrits au Lycée 1 qui sépare leurs élèves en fonction de leurs capacités magiques en deux catégories: la Première section qui comprend les meilleurs élèves qui sont appelés les « Bloom » (litt. « Fleur ») et la Seconde section les moins bons, dont les élèves sont surnommés les « Weed » (litt. « Mauvaise herbe ») ; Miyuki est retenue comme une élève de la Première section et est considérée comme l''une des meilleures étudiantes du lycée, tandis que Tatsuya est dans la Seconde section et considéré comme étant magiquement inepte. Peu importe comment, les connaissances techniques, les capacités de combat et les techniques magiques uniques de Tatsuya font que les gens le considèrent comme un élève médiocre selon le classement normalisé de l''école.', 36);

INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('Fullmetal Alchemist', 'Action/Aventure', 'Dans le pays d''Amestris, pays où l''alchimie est élevée au rang de science universelle, deux frères, Edward et Alphonse Elric, parcourent le pays à la recherche de la légendaire pierre philosophale. Leur père les a quittés et leur mère, Trisha Elric, meurt quelques années plus tard d''une maladie, laissant ses deux jeunes enfants derrière elle. Quelque temps plus tard, les deux frères tentent de la faire revenir grâce à l''alchimie, bravant la loi qui interdit formellement la transmutation humaine. Ils en payeront le prix fort. Edward, l''aîné, perdra sa jambe gauche, son petit frère son corps tout entier. Ed sacrifiera son bras droit en scellant l''âme de son petit frère Alphonse dans une armure. Edward décide de s''engager dans l''armée à l''âge de 12 ans en tant qu''alchimiste d''État, réussit l''examen haut la main et obtient son nom d''alchimiste : Fullmetal. Aidés du statut d''alchimiste d''État d''Edward, les deux frères chercheront, au péril de leur vie, la pierre qui leur rendra ce qu''ils ont perdu, mais le secret de la pierre philosophale est bien gardé…', 64);

INSERT INTO ANIME(nom,genre, description, nb_Ep) VALUES ('D Gray Man', 'Action/Surnaturel', 'Vers la fin d''un xixe siècle imaginaire et particulièrement gothique, le jeune Allen Walker est un exorciste appartenant à un ordre spécial appelé Congrégation de l''Ombre. Le but de cet ordre est d''affronter et d''éliminer des armes vivantes appelées Akuma (arme créée avec l''âme d''un mort et le corps d''un de ses proches), ainsi que leur créateur, le Comte Millénaire, dont le but est de détruire le monde et l’espèce humaine. Pour mener à bien ce combat, les exorcistes disposent chacun d''une Innocence, sorte d''arme personnelle fantastique extrêmement rare. Mais voila que le clan des Noé (aussi appelé Noah) (amis du Comte Millénaire), vient faire son apparition sur le champ de bataille des exorcistes. Ils sont des êtres semi-humains, se disent les descendants de Noe, et sont dotés d''une puissance phénoménale, mettant les exorcistes sur le tapis. La lutte est rude pour sortir le monde de l''emprise des ténèbres…', 116);
